spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  datasource:
    url: jdbc:h2:tcp://localhost/~/appcenterstudy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    open-in-view: true

cloud:
  aws:
    credentials:
      accessKey: AKIA6CHGTO2BWFIDJ24Q
      secretKey: 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
    s3:
      bucket: inu-appcenter-server-study
      thumbnailBucket: inu-appcenter-server-study-thumbnail
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
